apiVersion: v1
kind: Service
metadata:
  labels:
  name: sample-spring-kotlin
  namespace: next
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-spring-kotlin
