apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "pipelines-1.4"
  - name: IMAGE
    type: string
    description: image to be build from the code
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
   
  - name: update-stage-deployment-image
    taskRef:
      name: image-updater
    runAfter:
    - build-image
    params:
      - name: driver
        value: "github"
      - name: file-path
        value: "deployment.yaml"
      - name: image-repo
        value: $(reversewords_quay_repo)
      - name: new-image-url
        value: $(reversewords_quay_repo)
      - name: source-branch
        value: "stage"
      - name: source-repo
        value: $(imageBuilder_sourcerepo)
      - name: update-key
        value: "spec.template.spec.containers.0.image"
      - name: insecure
        value: "true"
      - name: branch-generate-name
        value: ""
